version: "3"
services:
  swap-service:
    image: pay-crypto-landing
    container_name: pay-crypto-landing
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:3000
    command: ["yarn", "start", "-p", "3000"]
